package com.landable.app.ui.home.dataModels

import java.io.Serializable

class Propertyraw : Serializable {
    var Additionalroom: String = ""
    var Landmark: String = ""
    var addedbyid: Int = 0
    var address1: String = ""
    var anyconstruction: String = ""
    var attachedbathroom: Int = 0
    var availfrommonth: Int = 0
    var availfromyear: Int = 0
    var balcony: Int = 0
    var bathroom: Int = 0
    var bedroom: Int = 0
    var boundrywall: String = ""
    var builduparea: Double = 0.0
    var bulityear: Int = 0
    var carpetarea: Double = 0.0
    var category: Int = 0
    var city: Int = 0
    var cost: Double = 0.0
    var costinword: String = ""
    var costperft: String = ""
    var country: Int = 0
    var createddate: String = ""
    var depositepercentage: Double = 0.0
    var description: String = ""
    var expirydate: String = ""
    var featured: Int = 0
    var floorforconstruction: Int = 0
    var floorno: String = ""
    var furnished: Int = 0
    var id: Int = 0
    var iscorner: String = ""
    var isingatedcolony: String = ""
    var lastremodalyear: String = ""
    var lat: String = ""
    var link: String = ""
    var lon: String = ""
    var maintenancecharge: Double = 0.0
    var maplocation: String = ""
    var openside: Int = 0
    var parking: Int = 0
    var pincode: String = ""
    var poolsize: String = ""
    var possessionstatus: Int = 0
    var projectid: Int = 0
    var propertyid: String = ""
    var rating: Double = 0.0
    var roadfacing: String = ""
    var saletype: Int = 0
    var securitydeposite: Double = 0.0
    var state: Int = 0
    var status: String = ""
    var subcategory: Int = 0
    var title: String = ""
    var totalarea: Double = 0.0
    var unit: String = ""
    var totalfloor :Int = 0
}